### ISSUE TITLE
Does this project supersede OMEdit?

### ISSUE THREAD

**Issue by zuckerruebe** [OpenModelica/OMWebEdit#12]
I've just seen that OMEdit has been archived on GitHub. Is this project OMEdit's continuation?

Cheers,
Damian

**Comment by lochel** [comment]
No, it's not. OMEdit's code got reintegrated i to the OpenModelica super-project some time ago. That's why the OMEdit repo is archived.

**Comment by adrpo** [comment]
No. It will be an OMEdit that works on the web, but it has quite some way to go until is usable.
